name: CI

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ############
  # Building #
  ############

  docker:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v2

      - run: make docker.image debug=no no-cache=yes
                  tag=build-${{ github.run_number }}

      - run: make docker.tar to-file=image.tar
                  tags=build-${{ github.run_number }}
      - uses: actions/upload-artifact@v3
        with:
          name: docker-${{ github.run_number }}
          path: image.tar
          retention-days: 1




  #############
  # Releasing #
  #############

  release-docker:
    name: Release Docker image
    needs: ["docker"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - uses: actions/download-artifact@v3
        with:
          name: docker-${{ github.run_number }}
      - run: make docker.untar from-file=image.tar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: make docker.tag tags=dev of=build-${{ github.run_number }}
      - run: make docker.push tags=dev
